from .comp_list_crawler import CompListCrawler
from .comp_overview_crawler import CompOverviewCrawler
from .comp_dis_list_crawler import CompDisListCrawler
from .comp_dis_details_crawler import CompDisDetailsCrawler